### PR TITLE
[FIX] When client close the websocket connection incorrectly, the sockjs server don't release the connection.

### PR DESCRIPTION
**Pull request by fatelei**
It will lead fd leak or memory leak in production environment.

I will show the detail of the problem later.

### CODE REVIEW

**Comment by boneyao** [comment]
+1

**Comment by fatelei** [comment]
The sockjs server is deployed behind the *nginx*.

Server code:

```
from tornado import web, ioloop
from sockjs.tornado import SockJSRouter, SockJSConnection


class EchoConnection(SockJSConnection):
    def on_message(self, msg):
        self.send(msg)

if __name__ == '__main__':

    EchoRouter = SockJSRouter(EchoConnection, '/chat')

    app = web.Application(EchoRouter.urls)
    app.listen(9999)
    ioloop.IOLoop.instance().start()
```

Client code

```
<html>
  <head>
    <script src="http://cdn.jsdelivr.net/sockjs/1.0.3/sockjs.min.js"></script>
    <script type="text/javascript">
      var sock = new SockJS('http://10.210.105.71/chat');
      sock.onopen = function () {
        console.log('open');
      };
      sock.onmessage = function (e) {
        console.log(e.data);
      };
      sock.onclose = function () {
        console.log('close');
      };
    </script>
  </head>
  <body>
    <input type="text" id="msg"/>
    <button id="send">Send</button>
    <script type="text/javascript">
      var ele = document.getElementById("send");
      var msg = document.getElementById("msg");
      ele.addEventListener("click", function (e) {
        sock.send(JSON.stringify({
          to: "b",
          payload: msg.value
        }))
      });
    </script>
  </body>
</html>
```

In `sockjs.tornado.session.Session`, I log `heartbeat` info to stdout:

```
    def _heartbeat(self):
        """Heartbeat callback"""
        if self.handler is not None:
            print('hearbeat')
            self.handler.send_pack(proto.HEARTBEAT)
        else:
            self.stop_heartbeat()
```

I start the `sockjs` server using this code, and the transport protocol is `websocket`. Meanwhile, I start a client to visit the page that connects to sockjs server. After a while, I can see the `heartbeat` from terminal.

selection_052

image1


Then I disable the network in client device, the `heartbeat` is still going on. So the sockjs thinks the client is always alive.

selection_053

image2

- - -

So I think behind a reverse proxy, the sockjs server need receive a echo heartbeat packet to judge whether a client is alive or not.

**Comment by fatelei** [comment]
@mrjoes  RT

**Comment by boneyao** [comment]
@fatelei 
  cc websocket ping pong
https://github.com/tornadoweb/tornado/blob/5268068cb5122bc689cd88dde0bb36137ffd0e1e/tornado/websocket.py#L268

**Comment by fatelei** [comment]
@boneyao sockjs doesn't using ping/pong as heartbeat protocol.

**Comment by fatelei** [comment]
@mrjoes Can you review this change?

**Pull request closed without merging**
